function data2 = import_csv(filename, delim, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   DATA2 = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   DATA2 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   data2 = importfile('data.csv', 2, 13);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/08/01 17:42:33

%% Initialize variables.
delimiter = delim;
if nargin<=3
    startRow = 1;
    endRow = inf;
end

%% Open the text file.
fileID = fopen(filename,'r');

%% Format for each line of text:
%   column1: text (%s)
%	column2: date (%s)
%   column3: text (%D)
% For more information, see the TEXTSCAN documentation.

z = textscan(fgetl(fileID),'%s','Delimiter',delimiter)
hdr = size(z{1},1);
formatSpec = [repmat('%q',1,hdr),'%[^\n\r]'];
%formatSpec = '%s%s%s%s%s%[^\n\r]';



%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
data2 = [dataArray{1:end-1}];
